services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"     # Internal listener (used by Docker services)
      - "29092:29092"   # External listener (used by host apps like Spring Boot)
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  flink-jobmanager:
    image: flink:1.20.0-scala_2.12
    ports:
      - "8081:8081"
    volumes:
      - ../../flink-job/target/:/opt/flink/jars
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.memory.process.size: 1024m
        taskmanager.memory.process.size: 2048m
        taskmanager.numberOfTaskSlots: 2
        s3.endpoint: http://minio:9000
        s3.path.style.access: true
        s3.access-key: minioadmin
        s3.secret-key: minioadmin

  flink-taskmanager:
    image: flink:1.20.0-scala_2.12
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.memory.process.size: 1024m
        taskmanager.memory.process.size: 2048m
        taskmanager.numberOfTaskSlots: 2
        s3.endpoint: http://minio:9000
        s3.path.style.access: true
        s3.access-key: minioadmin
        s3.secret-key: minioadmin

  flink-sql-client:
    image: flink:1.20.0-scala_2.12
    stdin_open: true
    tty: true
    entrypoint: ["./bin/sql-client.sh", "embedded"]
    depends_on:
      - flink-jobmanager
      - flink-taskmanager

volumes:
  minio-data:
