name: Deploy MSK Connect Connectors

on:
  push:
    branches:
      - main
      - kacomia
    paths:
      - 'kafka-connect/plugins/connectors/teams/**/*.json'

env:
  AWS_REGION: us-east-1

jobs:
  deploy-connectors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

#      - name: Set up AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.AWS_REGION }}

      - name: Get changed connector configs
        id: changes
        run: |
          echo "Finding changed connector config files..."

          set +e

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 2>/dev/null | grep 'kafka-connect/plugins/connectors/teams/.*/.*\.json')

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "Fallback to checking HEAD~1..."
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null | grep 'kafka-connect/plugins/connectors/teams/.*/.*\.json')
          fi

          set -e

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No changed connector files found."
            exit 0
          fi

          echo "$CHANGED_FILES" | while read file; do
            echo "$file" >> changed.txt
          done

          echo "Changed files:"
          cat changed.txt
      
      

      - name: Deploy changed connectors
        if: success()
        run: |
          if [[ ! -f changed.txt ]]; then
            echo "No connectors to deploy."
            exit 0
          fi

          while read CONFIG_PATH; do
            echo "Deploying connector from: $CONFIG_PATH"

            CONNECTOR_NAME=$(basename "$CONFIG_PATH" .json)

            echo "Connector name: $CONNECTOR_NAME"

            echo "Validating config..."
            jq empty "$CONFIG_PATH"

            echo "Checking if connector exists..."
            set +e
            aws kafkaconnect describe-connector \
              --connector-name "$CONNECTOR_NAME" \
              --query 'connectorState' \
              --output text 2>/dev/null
            EXISTS=$?
            set -e

            if [[ "$EXISTS" != "0" ]]; then
              echo "Connector $CONNECTOR_NAME does not exist. Creating..."
              aws kafkaconnect create-connector \
                --cli-input-json file://"$CONFIG_PATH"
            else
              echo "Connector $CONNECTOR_NAME exists. Updating..."
              CURRENT_VERSION=$(aws kafkaconnect describe-connector \
                --connector-name "$CONNECTOR_NAME" \
                --query 'connectorDescription.currentVersion' \
                --output text)

              aws kafkaconnect update-connector \
                --connector-name "$CONNECTOR_NAME" \
                --current-version "$CURRENT_VERSION" \
                --connector-configuration file://"$CONFIG_PATH"
            fi

            echo "Waiting for $CONNECTOR_NAME to become RUNNING..."

            ATTEMPTS=30
            SLEEP=10
            for ((i=1; i<=ATTEMPTS; i++)); do
              STATUS=$(aws kafkaconnect describe-connector \
                --connector-name "$CONNECTOR_NAME" \
                --query 'connectorState' \
                --output text)

              echo "Attempt $i: $STATUS"

              if [[ "$STATUS" == "RUNNING" ]]; then
                echo "✅ $CONNECTOR_NAME is RUNNING"
                break
              elif [[ "$STATUS" == "FAILED" || "$STATUS" == "DELETING" ]]; then
                echo "❌ $CONNECTOR_NAME failed or is being deleted"
                exit 1
              fi

              sleep $SLEEP
            done

          done < changed.txt
